import {
    attribute,
    autoGeneratedHashKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';

import { embed } from '@aws/dynamodb-data-mapper';
import { Models } from 'utilities-techsweave';


class OrderedProduct implements Models.Tables.IOrderedProduct {

    @attribute()
    quantity: number;

    @attribute()
    productId: string;

    @attribute()
    price: number;
}


/*
 * This class rappresent a product item in products table
 */
@table('orders-table')
class Order implements Models.Tables.IOrder {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    userId: string;

    @attribute({ defaultProvider: () => new Date() })
    date: Date;

    @attribute()
    status: string;

    // @attribute()
    // products?: Models.Tables.IOrderedProduct[];

    @attribute({ memberType: embed(OrderedProduct) })
    products?: Array<OrderedProduct>
}

export default Order;
