import {
    attribute,
    autoGeneratedHashKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';

import { Models } from 'utilities-techsweave';

/*
 * This class rappresent a product item in products table
 */
@table(process.env.ORDERS_TABLE)
class Order implements Models.Tables.IOrder {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    userId: string;

    @attribute({ defaultProvider: () => new Date() })
    date: Date;

    @attribute()
    status: string;

    @attribute()
    products?: Models.Tables.IOrderedProduct[];

}

export default Order;
